/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200ItemRemindersItem } from './getMedications200ItemRemindersItem';

export type GetMedications200Item = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  startDate: string;
  /** @nullable */
  duration: number | null;
  interval: number;
  isRecurring: boolean;
  totalQuantity: number;
  remainingQuantity: number;
  unit: string;
  dosageQuantity: number;
  userId: string;
  createdAt: string;
  updatedAt: string;
  reminders: GetMedications200ItemRemindersItem[];
};
