/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200MedicationsItem } from './getMedications200MedicationsItem';
import type { GetMedications200Groups } from './getMedications200Groups';

export type GetMedications200 = {
  medications: GetMedications200MedicationsItem[];
  groups: GetMedications200Groups;
};
