/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200GroupsLateItemMedicationsItemMedication } from './getMedications200GroupsLateItemMedicationsItemMedication';
import type { GetMedications200GroupsLateItemMedicationsItemReminder } from './getMedications200GroupsLateItemMedicationsItemReminder';

export type GetMedications200GroupsLateItemMedicationsItem = {
  medication: GetMedications200GroupsLateItemMedicationsItemMedication;
  reminder: GetMedications200GroupsLateItemMedicationsItemReminder;
  isLate: boolean;
};
