/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200AnyOfThreeGroupsLateItem } from './getMedications200AnyOfThreeGroupsLateItem';
import type { GetMedications200AnyOfThreeGroupsOnTimeItem } from './getMedications200AnyOfThreeGroupsOnTimeItem';

export type GetMedications200AnyOfThreeGroups = {
  late: GetMedications200AnyOfThreeGroupsLateItem[];
  onTime: GetMedications200AnyOfThreeGroupsOnTimeItem[];
};
