/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200AnyOfThreeGroupsLateItemMedicationsItemMedication } from './getMedications200AnyOfThreeGroupsLateItemMedicationsItemMedication';
import type { GetMedications200AnyOfThreeGroupsLateItemMedicationsItemReminder } from './getMedications200AnyOfThreeGroupsLateItemMedicationsItemReminder';

export type GetMedications200AnyOfThreeGroupsLateItemMedicationsItem = {
  medication: GetMedications200AnyOfThreeGroupsLateItemMedicationsItemMedication;
  reminder: GetMedications200AnyOfThreeGroupsLateItemMedicationsItemReminder;
  isLate: boolean;
};
