/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200GroupsLateItem } from './getMedications200GroupsLateItem';
import type { GetMedications200GroupsOnTimeItem } from './getMedications200GroupsOnTimeItem';

export type GetMedications200Groups = {
  late: GetMedications200GroupsLateItem[];
  onTime: GetMedications200GroupsOnTimeItem[];
};
