/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200GroupsOnTimeItemMedicationsItemMedication } from './getMedications200GroupsOnTimeItemMedicationsItemMedication';
import type { GetMedications200GroupsOnTimeItemMedicationsItemReminder } from './getMedications200GroupsOnTimeItemMedicationsItemReminder';

export type GetMedications200GroupsOnTimeItemMedicationsItem = {
  medication: GetMedications200GroupsOnTimeItemMedicationsItemMedication;
  reminder: GetMedications200GroupsOnTimeItemMedicationsItemReminder;
  isLate: boolean;
};
