/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type GetMedicationsId200Unit = typeof GetMedicationsId200Unit[keyof typeof GetMedicationsId200Unit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMedicationsId200Unit = {
  comprimidos: 'comprimidos',
  ml: 'ml',
  gotas: 'gotas',
  doses: 'doses',
} as const;
