/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200GroupsLateItemMedicationsItem } from './getMedications200GroupsLateItemMedicationsItem';

export type GetMedications200GroupsLateItem = {
  time: string;
  medications: GetMedications200GroupsLateItemMedicationsItem[];
};
