/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200AnyOfThreeMedicationsItem } from './getMedications200AnyOfThreeMedicationsItem';
import type { GetMedications200AnyOfThreeGroups } from './getMedications200AnyOfThreeGroups';

export type GetMedications200AnyOfThree = {
  medications: GetMedications200AnyOfThreeMedicationsItem[];
  groups: GetMedications200AnyOfThreeGroups;
};
