/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedications200AnyOfItem } from './getMedications200AnyOfItem';
import type { GetMedications200AnyOfThree } from './getMedications200AnyOfThree';

export type GetMedications200 = GetMedications200AnyOfItem[] | GetMedications200AnyOfThree;
