/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { GetMedicationsIdDetails200Medication } from './getMedicationsIdDetails200Medication';
import type { GetMedicationsIdDetails200RemindersItem } from './getMedicationsIdDetails200RemindersItem';

export type GetMedicationsIdDetails200 = {
  medication: GetMedicationsIdDetails200Medication;
  reminders: GetMedicationsIdDetails200RemindersItem[];
};
