/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type GetNotificationsWsWsClient = typeof GetNotificationsWsWsClient[keyof typeof GetNotificationsWsWsClient];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetNotificationsWsWsClient = {
  tauri: 'tauri',
} as const;
