/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type PatchMedicationsMedicationIdStock200 = {
  message: string;
  remainingQuantity: number;
};
