/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type PostRemindersMedicationIdReminders201Frequency = typeof PostRemindersMedicationIdReminders201Frequency[keyof typeof PostRemindersMedicationIdReminders201Frequency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostRemindersMedicationIdReminders201Frequency = {
  '6/6': '6/6',
  '8/8': '8/8',
  '12/12': '12/12',
  '24/24': '24/24',
} as const;
