/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { PostMedicationsBodyIntervalPreset } from './postMedicationsBodyIntervalPreset';
import type { PostMedicationsBodyUnit } from './postMedicationsBodyUnit';

export type PostMedicationsBody = {
  /** @minLength 2 */
  name: string;
  /** @nullable */
  description: string | null;
  startTime: string;
  intervalPreset: PostMedicationsBodyIntervalPreset;
  /** @minimum 0 */
  durationInDays: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  totalQuantity: number;
  unit: PostMedicationsBodyUnit;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  dosageQuantity: number;
};
