/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthGoogle200User = {
  id: string;
  email: string;
  name: string;
  /** @nullable */
  fcmToken: string | null;
  whatsappEnabled: boolean;
  /** @nullable */
  whatsappNumber: string | null;
  telegramEnabled: boolean;
  /** @nullable */
  telegramChatId: string | null;
  timezone: string;
  tauriEnabled: boolean;
  isDiabetic: boolean;
  hasHeartCondition: boolean;
  hasHypertension: boolean;
  /** @nullable */
  allergies: string | null;
  /** @nullable */
  observations: string | null;
  createdAt: string;
  updatedAt: string;
};
