/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister201User } from './postAuthRegister201User';

export type PostAuthRegister201 = {
  token: string;
  user: PostAuthRegister201User;
};
