/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { PostMedicationsBodyIntervalPreset } from './postMedicationsBodyIntervalPreset';

export type PostMedicationsBody = {
  /** @minLength 2 */
  name: string;
  description?: string;
  startTime: string;
  intervalPreset: PostMedicationsBodyIntervalPreset;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  durationInDays: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  totalQuantity: number;
  unit: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  dosageQuantity: number;
};
