/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */
import type { PostRemindersMedicationIdReminders201Frequency } from './postRemindersMedicationIdReminders201Frequency';

export type PostRemindersMedicationIdReminders201 = {
  id: string;
  medicationId: string;
  time: string;
  frequency: PostRemindersMedicationIdReminders201Frequency;
  daysOfWeek: number[];
  active: boolean;
  /** @nullable */
  lastTriggered: string | null;
  createdAt: string;
  updatedAt: string;
};
