/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * MedTime API
 * API do sistema MedTime para gestão de medicamentos e lembretes
 * OpenAPI spec version: 1.0.0
 */

export type PostMedications201 = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  startDate: string;
  interval: number;
  duration: number;
  totalQuantity: number;
  remainingQuantity: number;
  unit: string;
  dosageQuantity: number;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
